[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mGFD"
version = "0.9.1"
description = "mGFD (Meshless Generalized Finite Differences) is a high-performance Python ecosystem designed to solve Partial Differential Equations (PDEs) directly on unstructured point clouds, bypassing traditional mesh generation."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
    { name = "Gerardo Tinoco-Guerrero" },
    { name = "Francisco Javier Domínguez-Mota" },
    { name = "José Alberto Guzmán-Torres" },
    { email = "gerardo.tinoco@umich.mx"},
]


classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pyvista",
    "shapely",
    "opencv-python-headless",
]

[project.urls]
Homepage = "https://github.com/gstinoco/mGFD"
Repository = "https://github.com/gstinoco/mGFD.git"
Issues = "https://github.com/gstinoco/mGFD/issues"

[project.optional-dependencies]
test = [
    "pytest",
]
benchmark = [
    "psutil",
    "pandas",
]

[project.scripts]
mgfd-cloud = "mGFD.cloud_generator.cli.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
