"""
Plot Sweep — Visualizer for benchmark results

Overview:
    Parses the master summary CSV generated by the sweep and creates grouped bar charts
    to visualize the performance scaling of CPU vs CUDA implementations.

Public API:
    plot_sweep_metrics          Generate summary visualization plots from sweep metrics.

Credits:
    All the codes presented below were developed by:
        Dr. Gerardo Tinoco-Guerrero
        Dr. Francisco Javier Domínguez-Mota
        Dr. José Alberto Guzmán-Torres
        Universidad Michoacana de San Nicolás de Hidalgo
        gerardo.tinoco@umich.mx

    With the funding of:
        Secretary of Science, Humanities, Technology and Innovation, SECIHTI (Secretaria de Ciencia, Humanidades, Tecnología e Innovación). México.
        Coordination of Scientific Research, CIC-UMSNH (Coordinación de la Investigación Científica de la Universidad Michoacana de San Nicolás de Hidalgo, CIC-UMSNH). México.
        Aula CIMNE-Morelia. México.
        SIIIA-MATH: Soluciones de Ingeniería. México.

Date:
    May, 2024.
Last Modification:
    August, 2026.
"""

## Library importation.
import os                                                                                                                               # OS interfaces for file/directory paths.
import glob                                                                                                                             # File pattern matching.
import pandas as pd                                                                                                                     # Data manipulation.
import seaborn as sns                                                                                                                   # Statistical data visualization.
import matplotlib.pyplot as plt                                                                                                         # Plotting library.

from typing import Optional                                                                                                             # Type hints.

def find_latest_summary(results_root: str) -> Optional[str]:
    """
    find_latest_summary
    Finds the most recently modified sweep summary CSV in the results directory.

    Input:
        results_root    1           str             Path to the results directory.
        
    Output:
        csv_file        1           str             Path to the latest CSV, or None if empty.
    """
    files = glob.glob(os.path.join(results_root, 'sweep_summary_*.csv'))                                                                # Find all summary files.
    if not files:                                                                                                                       # If no files found.
        return None                                                                                                                     # Return None.
    return max(files, key=os.path.getctime)                                                                                             # Return the newest file.

def plot_sweep_results(results_root: str, out_dir: str) -> None:
    """
    plot_sweep_results
    Loads the sweep summary CSV and generates scaling and solver comparison plots.

    Input:
        results_root    1           str             Path to the directory containing the summary CSV.
        out_dir         1           str             Path to save the generated PNG plots.
        
    Output:
        None
    """
    csv_file = find_latest_summary(results_root)                                                                                        # Get the latest summary file.
    if not csv_file:                                                                                                                    # If no file was found.
        print(f"No sweep summary found in {results_root}")                                                                              # Print error message.
        return                                                                                                                          # Exit function.

    print(f"Loading {csv_file}...")                                                                                                     # Inform user.
    df = pd.read_csv(csv_file)                                                                                                          # Load CSV into DataFrame.
    
    time_col = None                                                                                                                     # Candidate time column.
    for candidate in ['Time_Secs', 'Time_Callable', 'Time_Array', 'Time_Pandas', 'Compute_Time_Secs']:                                  # Check known time metric column names.
        if candidate in df.columns and df[candidate].notna().any():                                                                     # If column exists and has non-null values.
            time_col = candidate                                                                                                        # Select target time column.
            break                                                                                                                       # Exit loop.
            
    if time_col is None:                                                                                                                # If no valid time column is found.
        print(f"No execution time metrics found in {csv_file}. Skipping sweep plots.")                                                  # Inform user.
        return                                                                                                                          # Exit function.
        
    print(f"Using '{time_col}' for performance plots.")                                                                                 # Inform user of metric used.

    def extract_device(config_id: str) -> str:                                                                                          # Helper function to extract device.
        parts = str(config_id).lower().split('_')                                                                                       # Split config string.
        if 'cuda' in parts or 'gpu' in parts: return 'CUDA'                                                                             # Check for CUDA.
        if 'cpu' in parts: return 'CPU'                                                                                                 # Check for CPU.
        return 'Unknown'                                                                                                                # Return default.
        
    def extract_config_label(config_id: str) -> str:                                                                                    # Helper to build legible configuration label.
        parts = str(config_id).split('_')                                                                                               # Split config ID.
        dev = 'CUDA' if any(p.lower() in ('cuda', 'gpu') for p in parts) else 'CPU'                                                     # Determine device.
        return f"{config_id} ({dev})"                                                                                                   # Return descriptive label.

    df['Device'] = df['Config_ID'].apply(extract_device)                                                                                # Map device column.
    df['Config'] = df['Config_ID'].apply(extract_config_label)                                                                          # Map configuration label column.
    
    os.makedirs(out_dir, exist_ok=True)                                                                                                 # Create output directory.
    sns.set_theme(style="whitegrid")                                                                                                    # Set plot style.
    
    plt.figure(figsize=(10, 6))                                                                                                         # Initialize figure.
    ax = sns.barplot(                                                                                                                   # Create bar plot.
        data=df,                                                                                                                        # Data source.
        x='Scale',                                                                                                                      # X axis.
        y=time_col,                                                                                                                     # Y axis.
        hue='Device',                                                                                                                   # Color grouping.
        errorbar=None,                                                                                                                  # Disable error bars.
        palette=['#4C72B0', '#55A868']                                                                                                  # Define colors.
    )                                                                                                                                   # End bar plot.
    
    plt.title('Performance Scaling: CPU vs CUDA', fontsize=16)                                                                          # Set title.
    plt.ylabel('Execution Time (seconds)', fontsize=12)                                                                                 # Set Y label.
    plt.xlabel('Scale (Density)', fontsize=12)                                                                                          # Set X label.
    plt.yscale('log')                                                                                                                   # Use logarithmic scale.
    
    for i in ax.containers:                                                                                                             # Iterate containers.
        ax.bar_label(i, fmt='%.2f', padding=3, fontsize=9)                                                                              # type: ignore
        
    out_path1 = os.path.join(out_dir, 'scaling_comparison.png')                                                                         # Path for first plot.
    plt.savefig(out_path1, dpi=300, bbox_inches='tight')                                                                                # Save plot.
    plt.close()                                                                                                                         # Close figure.
    print(f"Saved plot: {out_path1}")                                                                                                   # Inform user.
    
    if '3' in df['Scale'].astype(str).values:                                                                                           # Check if Scale 3 exists.
        df_large = df[df['Scale'].astype(str) == '3']                                                                                   # Filter for Scale 3.
        plt.figure(figsize=(12, 6))                                                                                                     # Initialize figure.
        
        df_large_copy = df_large.copy()                                                                                                 # Copy dataframe slice.
        df_large_copy = df_large_copy.sort_values(time_col)                                                                             # Sort by time.
        
        ax2 = sns.barplot(                                                                                                              # Create detailed bar plot.
            data=df_large_copy,                                                                                                         # Data source.
            x='Config',                                                                                                                 # X axis.
            y=time_col,                                                                                                                 # Y axis.
            hue='Device',                                                                                                               # Color grouping.
            dodge=False,                                                                                                                # Disable dodging.
            palette=['#4C72B0', '#55A868']                                                                                              # Define colors.
        )                                                                                                                               # End bar plot.
        
        plt.title('Solver Performance on Largest Scale (Scale 3)', fontsize=16)                                                         # Set title.
        plt.ylabel('Execution Time (seconds)', fontsize=12)                                                                             # Set Y label.
        plt.xlabel('Solver Configuration', fontsize=12)                                                                                 # Set X label.
        plt.xticks(rotation=45, ha='right')                                                                                             # Rotate X ticks.
        
        for i in ax2.containers:                                                                                                        # Iterate containers.
            ax2.bar_label(i, fmt='%.2f', padding=3, fontsize=10)                                                                        # type: ignore
            
        out_path2 = os.path.join(out_dir, 'large_scale_solvers.png')                                                                    # Path for second plot.
        plt.savefig(out_path2, dpi=300, bbox_inches='tight')                                                                            # Save plot.
        plt.close()                                                                                                                     # Close figure.
        print(f"Saved plot: {out_path2}")                                                                                               # Inform user.

if __name__ == '__main__':                                                                                                              # Main execution block.
    root = 'research/results'                                                                                                           # Define results root.
    out = os.path.join(root, 'sweep_plots')                                                                                             # Define output directory.
    plot_sweep_results(root, out)                                                                                                       # Run visualization.
