"""
Plot Sweep — Comprehensive Fair Visualizer for Benchmark Parameter Sweeps

Overview:
    Parses the master summary CSV generated by parameter sweeps and creates scientifically
    rigorous, disaggregated comparison plots across PDE physics, scales, devices, and mesh geometries.
    Produces fair performance scaling, paired GPU speedups, spatial error convergence, per-step efficiency,
    upwind stencil impact, and per-lake geometry breakdowns.

Public API:
    find_latest_summary             Finds the most recently modified sweep summary CSV in the results directory.
    extract_device                  Extract hardware device name (CPU or CUDA) from configuration string.
    extract_upwind                  Extract stencil directionality (Upwind, Symmetric, or Standard).
    plot_scaling_per_equation       Generate CPU vs CUDA runtime scaling bar charts per PDE equation.
    plot_speedups                   Generate paired CPU/CUDA speedup charts with break-even baseline.
    plot_error_convergence          Generate spatial error convergence curves (RMSE vs scale) per equation.
    plot_per_step_efficiency        Generate normalized compute time per discrete time step for transient PDEs.
    plot_upwind_comparison          Generate paired runtime and accuracy comparison for upwind vs symmetric stencils.
    plot_geometry_breakdowns        Generate per-lake performance breakdowns at the finest mesh scale.
    plot_sweep_results              Main orchestrator generating the complete comprehensive suite of fair sweep plots.

Credits:
    All the codes presented below were developed by:
        Dr. Gerardo Tinoco-Guerrero
        Dr. Francisco Javier Domínguez-Mota
        Dr. José Alberto Guzmán-Torres
        Universidad Michoacana de San Nicolás de Hidalgo
        gerardo.tinoco@umich.mx

    With the funding of:
        Secretary of Science, Humanities, Technology and Innovation, SECIHTI (Secretaria de Ciencia, Humanidades, Tecnología e Innovación). México.
        Coordination of Scientific Research, CIC-UMSNH (Coordinación de la Investigación Científica de la Universidad Michoacana de San Nicolás de Hidalgo, CIC-UMSNH). México.
        Aula CIMNE-Morelia. México.
        SIIIA-MATH: Soluciones de Ingeniería. México.

    Based on the theoretical concepts presented in:
        "mGFD: A meshless generalized finite difference method",
        Gerardo Tinoco-Guerrero, Francisco Javier Domínguez-Mota, José Alberto Guzmán-Torres, 
        Gabriela Pedraza-Jiménez, José Gerardo Tinoco-Ruiz,
        Computers & Mathematics with Applications, Volume 195 (2025) 396-418.
        https://doi.org/10.1016/j.camwa.2025.07.034

Date:
    May, 2024.
Last Modification:
    September, 2026.
"""

## Library importation.
import os                                                                                                                               # Operating system interfaces.
import glob                                                                                                                             # Filename pattern matching.
import logging                                                                                                                          # Logging framework.
import numpy as np                                                                                                                      # Core numerical operations.
import pandas as pd                                                                                                                     # Data manipulation and tabular analysis.
import seaborn as sns                                                                                                                   # Statistical data visualization.
import matplotlib.pyplot as plt                                                                                                         # Plotting engine.

from typing import Optional, List, Dict                                                                                                 # Type hinting.

logger = logging.getLogger(__name__)                                                                                                    # Module level logger.

PALETTE_DEVICE: Dict[str, str] = {                                                                                                      # Canonical color palette for hardware backends.
    'CPU':  '#2b5c8f',                                                                                                                  # Deep steel blue for CPU execution.
    'CUDA': '#2ca02c'                                                                                                                   # Vibrant green for GPU/CUDA acceleration.
}                                                                                                                                       # Execute statement.

def extract_device(config_id: str) -> str:
    """
    extract_device
    Extract hardware device name from configuration identifier.

    Input:
        config_id       1           str             Configuration identifier string (e.g. 'nvec_16_cuda').

    Output:
        device_name     1           str             Identified execution device ('CUDA', 'CPU', or 'Unknown').
    """
    parts = str(config_id).lower().split('_')                                                                                           # Tokenize configuration string.
    if 'cuda' in parts or 'gpu' in parts:                                                                                               # Detect GPU/CUDA marker.
        return 'CUDA'                                                                                                                   # Return CUDA identifier.
    if 'cpu' in parts:                                                                                                                  # Detect CPU marker.
        return 'CPU'                                                                                                                    # Return CPU identifier.
    return 'Unknown'                                                                                                                    # Return default fallback identifier.

def extract_upwind(config_id: str) -> str:
    """
    extract_upwind
    Extract stencil directionality scheme from configuration identifier.

    Input:
        config_id       1           str             Configuration identifier string.

    Output:
        upwind_scheme   1           str             Identified stencil scheme ('Upwind', 'Symmetric', or 'Standard').
    """
    cid = str(config_id).lower()                                                                                                        # Lowercase configuration string.
    if 'upwind_true' in cid:                                                                                                            # Evaluate upwind true presence.
        return 'Upwind'                                                                                                                 # Return Upwind identifier.
    if 'upwind_false' in cid:                                                                                                           # Evaluate upwind false presence.
        return 'Symmetric'                                                                                                              # Return Symmetric identifier.
    return 'Standard'                                                                                                                   # Return standard identifier.

def extract_config_label(config_id: str) -> str:
    """
    extract_config_label
    Build human-readable descriptive configuration label.

    Input:
        config_id       1           str             Configuration identifier string (e.g. 'nvec_16_cuda').

    Output:
        label           1           str             Formatted descriptive configuration label.
    """
    dev = extract_device(config_id)                                                                                                     # Extract hardware device.
    return f"{config_id} ({dev})"                                                                                                       # Return descriptive label.

def find_latest_summary(results_root: str) -> Optional[str]:
    """
    find_latest_summary
    Finds the most recently modified sweep summary CSV in the results directory.

    Input:
        results_root    1           str             Path to the results directory.
        
    Output:
        csv_file        1           str             Path to the latest CSV, or None if empty.
    """
    files = glob.glob(os.path.join(results_root, 'sweep_summary_*.csv'))                                                                # Find all summary files.
    if not files:                                                                                                                       # If no files found.
        return None                                                                                                                     # Return None.
    return max(files, key=os.path.getctime)                                                                                             # Return the newest file.

def plot_scaling_per_equation(df: pd.DataFrame, out_dir: str, time_col: str, verbose: bool = True) -> None:
    """
    plot_scaling_per_equation
    Generate fair, disaggregated CPU vs CUDA runtime scaling plots for each PDE equation.

    Input:
        df              N x C       DataFrame       Processed benchmark summary table.
        out_dir         1           str             Destination directory for plot output.
        time_col        1           str             Execution time column name.
        verbose         1           bool            If True, logs progress messages.

    Output:
        None
    """
    scaling_dir = os.path.join(out_dir, 'scaling')                                                                                      # Define subfolder for scaling plots.
    os.makedirs(scaling_dir, exist_ok=True)                                                                                             # Ensure subfolder exists.

    equations = sorted(df['Equation'].dropna().unique())                                                                                # Extract unique PDE equations.
    for eq in equations:                                                                                                                # Iterate across PDE equations.
        df_eq = df[df['Equation'] == eq].copy()                                                                                         # Filter table for target PDE.
        if df_eq.empty:                                                                                                                 # If no records present.
            continue                                                                                                                    # Skip execution.

        plt.figure(figsize=(9, 5))                                                                                                      # Initialize figure.
        ax = sns.barplot(                                                                                                               # Generate grouped bar chart.
            data      = df_eq,                                                                                                          # Data source.
            x         = 'Scale',                                                                                                        # Refinement scale on X axis.
            y         = time_col,                                                                                                       # Runtime on Y axis.
            hue       = 'Device',                                                                                                       # Group by hardware backend.
            palette   = PALETTE_DEVICE,                                                                                                 # Standard color palette.
            errorbar  = 'sd',                                                                                                           # Show standard deviation across geometries.
            capsize   = 0.1                                                                                                             # Error bar cap width.
        )                                                                                                                               # End barplot call.

        ax.set(yscale='log')                                                                                                            # Use logarithmic time scale.
        ax.set_title(f'Performance Scaling: {eq} (CPU vs CUDA)', fontsize=14, fontweight='bold')                                        # Set plot title.
        ax.set_xlabel('Mesh Refinement Scale', fontsize=11)                                                                             # Set X axis label.
        ax.set_ylabel('Execution Time [s] (Log Scale)', fontsize=11)                                                                    # Set Y axis label.
        ax.grid(True, which='both', linestyle='--', alpha=0.4)                                                                          # Enable subtle grid.

        for container in ax.containers:                                                                                                 # Annotate numeric values on bars.
            ax.bar_label(container, fmt='%.2f', padding=3, fontsize=9)                                                                  # type: ignore

        plot_path = os.path.join(scaling_dir, f'scaling_{eq}.png')                                                                      # Resolve output image path.
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')                                                                            # Save image file.
        plt.close()                                                                                                                     # Close figure.
        if verbose:                                                                                                                     # Check verbosity.
            print(f"Saved scaling plot: {plot_path}")                                                                                   # Log saved file.

    # Generate multi-panel scaling grid for global overview
    if len(equations) > 1:                                                                                                              # Check if multiple equations exist.
        cols = min(3, len(equations))                                                                                                   # Compute grid columns.
        rows = int(np.ceil(len(equations) / cols))                                                                                      # Compute grid rows.
        fig, axes = plt.subplots(rows, cols, figsize=(5.5 * cols, 4.5 * rows), squeeze=False)                                           # Initialize multi-panel figure.
        
        for idx, eq in enumerate(equations):                                                                                            # Populate each subplot.
            r, c  = divmod(idx, cols)                                                                                                   # Compute row and column index.
            ax    = axes[r, c]                                                                                                          # Select current axis.
            df_eq = df[df['Equation'] == eq]                                                                                            # Filter equation slice.
            
            sns.barplot(                                                                                                                # Generate subplot bar chart.
                data     = df_eq,                                                                                                       # Data source.
                x        = 'Scale',                                                                                                     # Refinement scale.
                y        = time_col,                                                                                                    # Runtime.
                hue      = 'Device',                                                                                                    # Grouping device.
                palette  = PALETTE_DEVICE,                                                                                              # Device colors.
                errorbar = None,                                                                                                        # Disable individual error bars.
                ax       = ax                                                                                                           # Target axis.
            )                                                                                                                           # End barplot call.
            
            ax.set(yscale='log')                                                                                                        # Log scale.
            ax.set_title(eq, fontsize=12, fontweight='bold')                                                                            # Subplot title.
            ax.set_xlabel('Scale', fontsize=10)                                                                                         # Subplot X label.
            ax.set_ylabel('Time [s] (Log)', fontsize=10)                                                                                # Subplot Y label.
            ax.grid(True, which='both', linestyle='--', alpha=0.3)                                                                      # Enable grid.

        for idx in range(len(equations), rows * cols):                                                                                  # Hide unused subplots.
            r, c = divmod(idx, cols)                                                                                                    # Extract coords.
            fig.delaxes(axes[r, c])                                                                                                     # Remove axis.

        plt.suptitle('Performance Scaling Across All PDE Physics', fontsize=16, fontweight='bold', y=1.02)                              # Main title.
        grid_path = os.path.join(scaling_dir, 'scaling_all_equations.png')                                                              # Resolve grid path.
        plt.savefig(grid_path, dpi=300, bbox_inches='tight')                                                                            # Save grid plot.
        plt.close()                                                                                                                     # Close figure.
        if verbose:                                                                                                                     # Check verbosity.
            print(f"Saved scaling grid: {grid_path}")                                                                                   # Log saved file.

def plot_speedups(df: pd.DataFrame, out_dir: str, time_col: str, verbose: bool = True) -> None:
    """
    plot_speedups
    Compute paired CPU vs CUDA execution times and plot real GPU acceleration factors.

    Input:
        df              N x C       DataFrame       Processed benchmark summary table.
        out_dir         1           str             Destination directory for plot output.
        time_col        1           str             Execution time column name.
        verbose         1           bool            If True, logs progress messages.

    Output:
        None
    """
    speedup_dir = os.path.join(out_dir, 'speedup')                                                                                      # Define subfolder for speedup plots.
    os.makedirs(speedup_dir, exist_ok=True)                                                                                             # Ensure subfolder exists.

    df_cpu = df[df['Device'] == 'CPU'].copy()                                                                                           # Extract CPU runs.
    df_gpu = df[df['Device'] == 'CUDA'].copy()                                                                                          # Extract CUDA runs.

    if df_cpu.empty or df_gpu.empty:                                                                                                    # Check if both devices present.
        if verbose:                                                                                                                     # Check verbosity.
            print("Skipping speedup plots: requires both CPU and CUDA records.")                                                        # Inform user.
        return                                                                                                                          # Exit routine.

    merge_keys = ['Equation', 'Dataset', 'Scale', 'Upwind_Scheme']                                                                      # Key columns to pair runs.
    paired     = pd.merge(df_cpu, df_gpu, on=merge_keys, suffixes=('_CPU', '_CUDA'))                                                    # Merge paired executions.
    if paired.empty:                                                                                                                    # If pairing yielded no matches.
        return                                                                                                                          # Exit routine.

    paired['Speedup'] = paired[f'{time_col}_CPU'] / paired[f'{time_col}_CUDA']                                                          # Compute paired speedup factor.

    equations = sorted(paired['Equation'].dropna().unique())                                                                            # Extract unique equations.
    for eq in equations:                                                                                                                # Iterate equations.
        p_eq = paired[paired['Equation'] == eq].copy()                                                                                  # Filter equation slice.
        if p_eq.empty:                                                                                                                  # If empty.
            continue                                                                                                                    # Skip.

        plt.figure(figsize=(9, 5))                                                                                                      # Initialize figure.
        ax = sns.barplot(                                                                                                               # Generate speedup bar chart.
            data      = p_eq,                                                                                                           # Data source.
            x         = 'Scale',                                                                                                        # Refinement scale on X axis.
            y         = 'Speedup',                                                                                                      # Speedup factor on Y axis.
            hue       = 'Scale',                                                                                                        # Hue mapped to scale.
            palette   = 'Blues_d',                                                                                                      # Blue shade gradient.
            legend    = False,                                                                                                          # Disable legend.
            errorbar  = 'sd',                                                                                                           # Standard deviation across geometries.
            capsize   = 0.1                                                                                                             # Cap size.
        )                                                                                                                               # End barplot call.

        ax.axhline(1.0, color='#d62728', linestyle='--', linewidth=1.8, label='Baseline (1.0x - Parity)')                               # Draw break-even line.
        ax.set_title(f'GPU Acceleration Speedup: {eq} (Time_CPU / Time_CUDA)', fontsize=14, fontweight='bold')                          # Set plot title.
        ax.set_xlabel('Mesh Refinement Scale', fontsize=11)                                                                             # Set X label.
        ax.set_ylabel('Speedup Factor [x] (>1 = GPU Win)', fontsize=11)                                                                 # Set Y label.
        ax.legend(loc='upper left')                                                                                                     # Display legend.
        ax.grid(True, which='both', linestyle='--', alpha=0.4)                                                                          # Enable grid.

        for container in ax.containers:                                                                                                 # Annotate numeric values on bars.
            ax.bar_label(container, fmt='%.2fx', padding=3, fontsize=9)                                                                 # type: ignore

        plot_path = os.path.join(speedup_dir, f'speedup_{eq}.png')                                                                      # Resolve image path.
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')                                                                            # Save image.
        plt.close()                                                                                                                     # Close figure.
        if verbose:                                                                                                                     # Check verbosity.
            print(f"Saved speedup plot: {plot_path}")                                                                                   # Log saved file.

    # Generate comprehensive summary speedup plot across all equations
    plt.figure(figsize=(10, 6))                                                                                                         # Initialize figure.
    ax_sum = sns.barplot(                                                                                                               # Comparative speedup summary.
        data     = paired,                                                                                                              # Data source.
        x        = 'Scale',                                                                                                             # Refinement scale.
        y        = 'Speedup',                                                                                                           # Speedup factor.
        hue      = 'Equation',                                                                                                          # Group by PDE equation.
        palette  = 'Set2',                                                                                                              # Set2 qualitative palette.
        errorbar = None                                                                                                                 # Disable error bars.
    )                                                                                                                                   # End barplot call.

    ax_sum.axhline(1.0, color='#d62728', linestyle='--', linewidth=1.8, label='Baseline (1.0x - Parity)')                               # Draw break-even line.
    ax_sum.set_title('Comparative GPU Acceleration Speedup Across All Physics', fontsize=15, fontweight='bold')                         # Set plot title.
    ax_sum.set_xlabel('Mesh Refinement Scale', fontsize=12)                                                                             # Set X label.
    ax_sum.set_ylabel('Mean Speedup Factor [x]', fontsize=12)                                                                           # Set Y label.
    ax_sum.legend(loc='upper left', title='PDE Physics')                                                                                # Place legend.
    ax_sum.grid(True, which='both', linestyle='--', alpha=0.4)                                                                          # Enable grid.

    for container in ax_sum.containers:                                                                                                 # Annotate speedup values.
        ax_sum.bar_label(container, fmt='%.2fx', padding=3, fontsize=8)                                                                 # type: ignore

    summary_path = os.path.join(speedup_dir, 'speedup_summary.png')                                                                     # Resolve summary path.
    plt.savefig(summary_path, dpi=300, bbox_inches='tight')                                                                             # Save summary image.
    plt.close()                                                                                                                         # Close figure.
    if verbose:                                                                                                                         # Check verbosity.
        print(f"Saved speedup summary: {summary_path}")                                                                                 # Log saved file.

def plot_error_convergence(df: pd.DataFrame, out_dir: str, verbose: bool = True) -> None:
    """
    plot_error_convergence
    Generate spatial error convergence curves (RMSE vs scale) disaggregated per PDE equation.

    Input:
        df              N x C       DataFrame       Processed benchmark summary table.
        out_dir         1           str             Destination directory for plot output.
        verbose         1           bool            If True, logs progress messages.

    Output:
        None
    """
    if 'Error' not in df.columns or df['Error'].dropna().empty:                                                                         # Check error metric presence.
        return                                                                                                                          # Exit routine.

    conv_dir = os.path.join(out_dir, 'convergence')                                                                                     # Define subfolder for convergence plots.
    os.makedirs(conv_dir, exist_ok=True)                                                                                                # Ensure subfolder exists.

    equations = sorted(df['Equation'].dropna().unique())                                                                                # Extract unique equations.
    for eq in equations:                                                                                                                # Iterate equations.
        df_eq = df[(df['Equation'] == eq) & df['Error'].notna() & (df['Error'] > 0)].copy()                                             # Filter valid positive errors.
        if df_eq.empty:                                                                                                                 # If empty.
            continue                                                                                                                    # Skip.

        plt.figure(figsize=(9, 5))                                                                                                      # Initialize figure.
        ax = sns.lineplot(                                                                                                              # Generate line plot.
            data       = df_eq,                                                                                                         # Data source.
            x          = 'Scale',                                                                                                       # Refinement scale.
            y          = 'Error',                                                                                                       # Root Mean Square Error.
            hue        = 'Device' if df_eq['Device'].nunique() > 1 else None,                                                           # Group by device if applicable.
            palette    = PALETTE_DEVICE if df_eq['Device'].nunique() > 1 else None,                                                     # Apply device palette.
            marker     = 'o',                                                                                                           # Circle markers.
            markersize = 8,                                                                                                             # Marker size.
            linewidth  = 2.2,                                                                                                           # Line width.
            errorbar   = 'sd'                                                                                                           # Show standard deviation.
        )                                                                                                                               # End lineplot call.

        ax.set(yscale='log')                                                                                                            # Use logarithmic error scale.
        ax.set_title(f'Spatial Error Convergence: {eq}', fontsize=14, fontweight='bold')                                                # Set plot title.
        ax.set_xlabel('Mesh Refinement Scale', fontsize=11)                                                                             # Set X label.
        ax.set_ylabel('Root Mean Square Error (RMSE) [Log Scale]', fontsize=11)                                                         # Set Y label.
        ax.grid(True, which='both', linestyle='--', alpha=0.4)                                                                          # Enable grid.

        plot_path = os.path.join(conv_dir, f'convergence_{eq}.png')                                                                     # Resolve output path.
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')                                                                            # Save image file.
        plt.close()                                                                                                                     # Close figure.
        if verbose:                                                                                                                     # Check verbosity.
            print(f"Saved convergence plot: {plot_path}")                                                                               # Log saved file.

    # Generate multi-panel convergence overview
    valid_eqs = [eq for eq in equations if not df[(df['Equation'] == eq) & df['Error'].notna() & (df['Error'] > 0)].empty]              # Valid equations.
    if len(valid_eqs) > 1:                                                                                                              # Check if multiple equations exist.
        cols      = min(3, len(valid_eqs))                                                                                              # Compute columns.
        rows      = int(np.ceil(len(valid_eqs) / cols))                                                                                 # Compute rows.
        fig, axes = plt.subplots(rows, cols, figsize=(5.5 * cols, 4.5 * rows), squeeze=False)                                           # Initialize multi-panel figure.

        for idx, eq in enumerate(valid_eqs):                                                                                            # Iterate valid equations.
            r, c  = divmod(idx, cols)                                                                                                   # Compute coords.
            ax    = axes[r, c]                                                                                                          # Select axis.
            df_eq = df[(df['Equation'] == eq) & df['Error'].notna() & (df['Error'] > 0)]                                                # Filter equation slice.

            sns.lineplot(                                                                                                               # Generate subplot line chart.
                data       = df_eq,                                                                                                     # Data source.
                x          = 'Scale',                                                                                                   # Refinement scale.
                y          = 'Error',                                                                                                   # Error metric.
                hue        = 'Device' if df_eq['Device'].nunique() > 1 else None,                                                       # Device grouping.
                palette    = PALETTE_DEVICE if df_eq['Device'].nunique() > 1 else None,                                                 # Device palette.
                marker     = 's',                                                                                                       # Square markers.
                markersize = 7,                                                                                                         # Marker size.
                linewidth  = 2.0,                                                                                                       # Line width.
                errorbar   = None,                                                                                                      # Disable error bars.
                ax         = ax                                                                                                         # Target axis.
            )                                                                                                                           # End lineplot call.

            ax.set(yscale='log')                                                                                                        # Log scale.
            ax.set_title(eq, fontsize=12, fontweight='bold')                                                                            # Subplot title.
            ax.set_xlabel('Scale', fontsize=10)                                                                                         # Subplot X label.
            ax.set_ylabel('RMSE (Log)', fontsize=10)                                                                                    # Subplot Y label.
            ax.grid(True, which='both', linestyle='--', alpha=0.3)                                                                      # Enable grid.

        for idx in range(len(valid_eqs), rows * cols):                                                                                  # Hide unused subplots.
            r, c = divmod(idx, cols)                                                                                                    # Extract coords.
            fig.delaxes(axes[r, c])                                                                                                     # Remove axis.

        plt.suptitle('Spatial Error Convergence Across PDE Physics', fontsize=16, fontweight='bold', y=1.02)                            # Main title.
        grid_path = os.path.join(conv_dir, 'convergence_all_equations.png')                                                             # Resolve grid path.
        plt.savefig(grid_path, dpi=300, bbox_inches='tight')                                                                            # Save grid image.
        plt.close()                                                                                                                     # Close figure.
        if verbose:                                                                                                                     # Check verbosity.
            print(f"Saved convergence grid: {grid_path}")                                                                               # Log saved file.

def plot_per_step_efficiency(df: pd.DataFrame, out_dir: str, time_col: str, verbose: bool = True) -> None:
    """
    plot_per_step_efficiency
    Generate normalized compute time per discrete time step for transient PDEs.

    Input:
        df              N x C       DataFrame       Processed benchmark summary table.
        out_dir         1           str             Destination directory for plot output.
        time_col        1           str             Execution time column name.
        verbose         1           bool            If True, logs progress messages.

    Output:
        None
    """
    if 'Time_Steps' not in df.columns:                                                                                                  # Check step count column presence.
        return                                                                                                                          # Exit routine.

    df_trans = df[df['Time_Steps'].notna() & (df['Time_Steps'] > 0)].copy()                                                             # Filter transient records with steps.
    if df_trans.empty:                                                                                                                  # If empty.
        return                                                                                                                          # Exit routine.

    step_dir = os.path.join(out_dir, 'per_step')                                                                                        # Define subfolder for per-step plots.
    os.makedirs(step_dir, exist_ok=True)                                                                                                # Ensure subfolder exists.

    df_trans['Time_Per_Step_ms'] = (df_trans[time_col] / df_trans['Time_Steps']) * 1000.0                                               # Compute milliseconds per time step.

    equations = sorted(df_trans['Equation'].dropna().unique())                                                                          # Extract transient equations.
    for eq in equations:                                                                                                                # Iterate equations.
        df_eq = df_trans[df_trans['Equation'] == eq].copy()                                                                             # Filter equation slice.
        if df_eq.empty:                                                                                                                 # If empty.
            continue                                                                                                                    # Skip.

        plt.figure(figsize=(9, 5))                                                                                                      # Initialize figure.
        ax = sns.barplot(                                                                                                               # Generate per-step cost bar chart.
            data     = df_eq,                                                                                                           # Data source.
            x        = 'Scale',                                                                                                         # Refinement scale.
            y        = 'Time_Per_Step_ms',                                                                                              # Milliseconds per step.
            hue      = 'Device',                                                                                                        # Hardware grouping.
            palette  = PALETTE_DEVICE,                                                                                                  # Device colors.
            errorbar = 'sd',                                                                                                            # Standard deviation across geometries.
            capsize  = 0.1                                                                                                              # Cap size.
        )                                                                                                                               # End barplot call.

        ax.set(yscale='log')                                                                                                            # Use logarithmic cost scale.
        ax.set_title(f'Cost per Time Step: {eq} (CPU vs CUDA)', fontsize=14, fontweight='bold')                                         # Set plot title.
        ax.set_xlabel('Mesh Refinement Scale', fontsize=11)                                                                             # Set X label.
        ax.set_ylabel('Time per Step [ms] (Log Scale)', fontsize=11)                                                                    # Set Y label.
        ax.grid(True, which='both', linestyle='--', alpha=0.4)                                                                          # Enable grid.

        for container in ax.containers:                                                                                                 # Annotate numeric values on bars.
            ax.bar_label(container, fmt='%.3f ms', padding=3, fontsize=8)                                                               # type: ignore

        plot_path = os.path.join(step_dir, f'per_step_{eq}.png')                                                                        # Resolve image path.
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')                                                                            # Save image file.
        plt.close()                                                                                                                     # Close figure.
        if verbose:                                                                                                                     # Check verbosity.
            print(f"Saved per-step plot: {plot_path}")                                                                                  # Log saved file.

def plot_upwind_comparison(df: pd.DataFrame, out_dir: str, time_col: str, verbose: bool = True) -> None:
    """
    plot_upwind_comparison
    Generate paired runtime and accuracy comparison for upwind vs symmetric stencils.

    Input:
        df              N x C       DataFrame       Processed benchmark summary table.
        out_dir         1           str             Destination directory for plot output.
        time_col        1           str             Execution time column name.
        verbose         1           bool            If True, logs progress messages.

    Output:
        None
    """
    upwind_dir = os.path.join(out_dir, 'upwind_comparison')                                                                             # Define subfolder for upwind plots.
    os.makedirs(upwind_dir, exist_ok=True)                                                                                              # Ensure subfolder exists.

    equations = sorted(df['Equation'].dropna().unique())                                                                                # Extract unique equations.
    for eq in equations:                                                                                                                # Iterate equations.
        df_eq = df[(df['Equation'] == eq) & (df['Upwind_Scheme'].isin(['Upwind', 'Symmetric']))].copy()                                 # Filter upwind comparison rows.
        if df_eq['Upwind_Scheme'].nunique() < 2:                                                                                        # If only one scheme evaluated.
            continue                                                                                                                    # Skip execution.

        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))                                                                           # Initialize two-panel figure.

        # Panel 1: Execution Time Comparison
        sns.barplot(                                                                                                                    # Generate runtime comparison.
            data     = df_eq,                                                                                                           # Data source.
            x        = 'Scale',                                                                                                         # Refinement scale.
            y        = time_col,                                                                                                        # Execution time.
            hue      = 'Upwind_Scheme',                                                                                                 # Group by stencil scheme.
            palette  = ['#1f77b4', '#ff7f0e'],                                                                                          # Blue vs Orange palette.
            errorbar = None,                                                                                                            # Disable error bars.
            ax       = ax1                                                                                                              # Target left axis.
        )                                                                                                                               # End barplot call.

        ax1.set(yscale='log')                                                                                                           # Log scale.
        ax1.set_title(f'Runtime Impact: {eq}', fontsize=12, fontweight='bold')                                                          # Left title.
        ax1.set_xlabel('Mesh Refinement Scale', fontsize=10)                                                                            # Left X label.
        ax1.set_ylabel('Execution Time [s] (Log)', fontsize=10)                                                                         # Left Y label.
        ax1.grid(True, which='both', linestyle='--', alpha=0.4)                                                                         # Enable grid.

        # Panel 2: Numerical Error Comparison
        if 'Error' in df_eq.columns and not df_eq['Error'].dropna().empty:                                                              # Check error column presence.
            sns.barplot(                                                                                                                # Generate error comparison.
                data     = df_eq,                                                                                                       # Data source.
                x        = 'Scale',                                                                                                     # Refinement scale.
                y        = 'Error',                                                                                                     # Error metric.
                hue      = 'Upwind_Scheme',                                                                                             # Group by stencil scheme.
                palette  = ['#1f77b4', '#ff7f0e'],                                                                                      # Match palette.
                errorbar = None,                                                                                                        # Disable error bars.
                ax       = ax2                                                                                                          # Target right axis.
            )                                                                                                                           # End barplot call.

            ax2.set(yscale='log')                                                                                                       # Log scale.
            ax2.set_title(f'Accuracy Impact: {eq}', fontsize=12, fontweight='bold')                                                     # Right title.
            ax2.set_xlabel('Mesh Refinement Scale', fontsize=10)                                                                        # Right X label.
            ax2.set_ylabel('Error (RMSE) [Log]', fontsize=10)                                                                           # Right Y label.
            ax2.grid(True, which='both', linestyle='--', alpha=0.4)                                                                     # Enable grid.
        else:                                                                                                                           # If error not present.
            ax2.text(0.5, 0.5, 'Error metrics unavailable', ha='center', va='center', transform=ax2.transAxes)                          # Display message.

        plt.suptitle(f'Stencil Directionality Analysis: {eq} (Upwind vs Symmetric)', fontsize=14, fontweight='bold', y=1.02)            # Main figure title.
        plot_path = os.path.join(upwind_dir, f'upwind_impact_{eq}.png')                                                                 # Resolve plot path.
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')                                                                            # Save image file.
        plt.close()                                                                                                                     # Close figure.
        if verbose:                                                                                                                     # Check verbosity.
            print(f"Saved upwind comparison: {plot_path}")                                                                              # Log saved file.

def plot_geometry_breakdowns(df: pd.DataFrame, out_dir: str, time_col: str, verbose: bool = True) -> None:
    """
    plot_geometry_breakdowns
    Generate per-lake performance breakdowns at the finest mesh scale.

    Input:
        df              N x C       DataFrame       Processed benchmark summary table.
        out_dir         1           str             Destination directory for plot output.
        time_col        1           str             Execution time column name.
        verbose         1           bool            If True, logs progress messages.

    Output:
        None
    """
    geom_dir = os.path.join(out_dir, 'geometry_breakdown')                                                                              # Define subfolder for geometry plots.
    os.makedirs(geom_dir, exist_ok=True)                                                                                                # Ensure subfolder exists.

    for target_scale in ['4', '3', '2']:                                                                                                # Check finest available scale.
        df_scale = df[df['Scale'] == target_scale]                                                                                      # Filter scale records.
        if not df_scale.empty:                                                                                                          # If records present.
            finest_scale = target_scale                                                                                                 # Assign finest scale.
            break                                                                                                                       # Exit search.
    else:                                                                                                                               # If no scale found.
        return                                                                                                                          # Exit routine.

    equations = sorted(df['Equation'].dropna().unique())                                                                                # Extract unique equations.
    for eq in equations:                                                                                                                # Iterate equations.
        df_eq = df[(df['Equation'] == eq) & (df['Scale'] == finest_scale)].copy()                                                       # Filter equation and scale.
        if df_eq.empty:                                                                                                                 # If empty.
            continue                                                                                                                    # Skip.

        lake_order = df_eq.groupby('Dataset')[time_col].mean().sort_values(ascending=False).index                                       # Order lakes by compute time.
        plt.figure(figsize=(10, max(6, len(lake_order) * 0.35)))                                                                        # Scale figure height to lake count.
        
        ax = sns.barplot(                                                                                                               # Generate horizontal bar plot.
            data    = df_eq,                                                                                                            # Data source.
            y       = 'Dataset',                                                                                                        # Lakes on Y axis.
            x       = time_col,                                                                                                         # Execution time on X axis.
            hue     = 'Device',                                                                                                         # Hardware grouping.
            order   = lake_order,                                                                                                       # Sorted order.
            palette = PALETTE_DEVICE,                                                                                                   # Standard colors.
            dodge   = True                                                                                                              # Enable dodging between devices.
        )                                                                                                                               # End barplot call.

        ax.set(xscale='log')                                                                                                            # Log scale for wide execution ranges.
        ax.set_title(f'Performance Across Lake Geometries: {eq} (Scale {finest_scale})', fontsize=13, fontweight='bold')                # Set plot title.
        ax.set_xlabel('Execution Time [s] (Log Scale)', fontsize=11)                                                                    # Set X label.
        ax.set_ylabel('Lake / Geographic Dataset', fontsize=11)                                                                         # Set Y label.
        ax.grid(True, which='both', linestyle='--', alpha=0.4)                                                                          # Enable grid.

        plot_path = os.path.join(geom_dir, f'geometry_{eq}_scale_{finest_scale}.png')                                                   # Resolve image path.
        plt.savefig(plot_path, dpi=300, bbox_inches='tight')                                                                            # Save image file.
        plt.close()                                                                                                                     # Close figure.
        if verbose:                                                                                                                     # Check verbosity.
            print(f"Saved geometry breakdown: {plot_path}")                                                                             # Log saved file.

def plot_sweep_results(results_root: str, out_dir: str, verbose: bool = True) -> None:
    """
    plot_sweep_results
    Main orchestrator generating the complete comprehensive suite of fair sweep plots.

    Loads the sweep summary CSV, enriches columns with device and scheme classifiers,
    and dispatches specialized plotting modules for scaling, speedups, error convergence,
    per-step cost, upwind schemes, and per-lake geometry comparisons.

    Input:
        results_root    1           str             Path to the results directory containing summary CSV.
        out_dir         1           str             Path to output directory where plots are saved.
        verbose         1           bool            If True, prints progress and output messages.
        
    Output:
        None
    """
    # 1. Summary file resolution
    csv_file = find_latest_summary(results_root)                                                                                        # Get the latest summary file.
    if not csv_file:                                                                                                                    # If no file was found.
        if verbose:                                                                                                                     # Check verbosity.
            print(f"No sweep summary found in {results_root}")                                                                          # Print error message.
        return                                                                                                                          # Exit function.

    if verbose:                                                                                                                         # Check verbosity.
        print(f"\n==================================================")                                                                  # Visual banner.
        print(f"Loading Sweep Summary: {os.path.basename(csv_file)}")                                                                   # Inform user.
        print(f"==================================================")                                                                    # Visual banner.

    df = pd.read_csv(csv_file)                                                                                                          # Load CSV into DataFrame.
    if df.empty:                                                                                                                        # If table is empty.
        if verbose:                                                                                                                     # Check verbosity.
            print("Sweep summary file is empty.")                                                                                       # Inform user.
        return                                                                                                                          # Exit function.

    # 2. Execution metric and label normalization
    time_col = 'Time_Secs' if ('Time_Secs' in df.columns and df['Time_Secs'].notna().any()) else None                                   # Extract execution time column.
    if time_col is None:                                                                                                                # If time column missing.
        if verbose:                                                                                                                     # Check verbosity.
            print(f"No 'Time_Secs' metric found in {csv_file}. Skipping sweep plots.")                                                  # Inform user.
        return                                                                                                                          # Exit function.

    df['Scale']          = df['Scale'].astype(str)                                                                                      # Normalize Scale column to string.
    df['Device']         = df['Config_ID'].apply(extract_device)                                                                        # Classify hardware device.
    df['Upwind_Scheme']  = df['Config_ID'].apply(extract_upwind)                                                                        # Classify stencil directionality.
    
    # Standardize error metric across stationary and transient solvers
    if 'Time_Mean_RMSE' in df.columns and 'RMSE' in df.columns:                                                                         # If both metrics present.
        df['Error'] = df['Time_Mean_RMSE'].fillna(df['RMSE'])                                                                           # Merge into single Error column.
    elif 'Time_Mean_RMSE' in df.columns:                                                                                                # If only transient present.
        df['Error'] = df['Time_Mean_RMSE']                                                                                              # Assign transient error.
    elif 'RMSE' in df.columns:                                                                                                          # If only stationary present.
        df['Error'] = df['RMSE']                                                                                                        # Assign stationary error.
    else:                                                                                                                               # Fallback if neither present.
        df['Error'] = np.nan                                                                                                            # Assign NaN.

    # 3. Initialize visual theme
    sns.set_theme(style="whitegrid")                                                                                                    # Standard whitegrid visual theme.
    os.makedirs(out_dir, exist_ok=True)                                                                                                 # Ensure main output directory exists.

    # 4. Dispatch fair disaggregated analysis modules
    if verbose:                                                                                                                         # Check verbosity.
        print("\n[1/6] Generating Performance Scaling Plots (per PDE)...")                                                              # Inform step.
    plot_scaling_per_equation(df, out_dir, time_col, verbose=verbose)                                                                   # Execute scaling module.

    if verbose:                                                                                                                         # Check verbosity.
        print("\n[2/6] Generating Paired GPU Acceleration Speedups...")                                                                 # Inform step.
    plot_speedups(df, out_dir, time_col, verbose=verbose)                                                                               # Execute speedup module.

    if verbose:                                                                                                                         # Check verbosity.
        print("\n[3/6] Generating Spatial Error Convergence Curves...")                                                                 # Inform step.
    plot_error_convergence(df, out_dir, verbose=verbose)                                                                                # Execute convergence module.

    if verbose:                                                                                                                         # Check verbosity.
        print("\n[4/6] Generating Per-Step Efficiency Visualizations...")                                                               # Inform step.
    plot_per_step_efficiency(df, out_dir, time_col, verbose=verbose)                                                                    # Execute per-step module.

    if verbose:                                                                                                                         # Check verbosity.
        print("\n[5/6] Generating Stencil Directionality Impact Plots (Upwind vs Symmetric)...")                                        # Inform step.
    plot_upwind_comparison(df, out_dir, time_col, verbose=verbose)                                                                      # Execute upwind module.

    if verbose:                                                                                                                         # Check verbosity.
        print("\n[6/6] Generating Per-Lake Geometry Breakdowns (Finest Scale)...")                                                      # Inform step.
    plot_geometry_breakdowns(df, out_dir, time_col, verbose=verbose)                                                                    # Execute geometry module.

    if verbose:                                                                                                                         # Check verbosity.
        print(f"\nCompleted comprehensive sweep plot generation in:")                                                                   # Inform success.
        print(f" -> {out_dir}\n")                                                                                                       # Output path.

if __name__ == '__main__':                                                                                                              # Main execution block.
    root = 'research/results'                                                                                                           # Define results root directory.
    out  = os.path.join(root, 'sweep_plots')                                                                                            # Define plots output directory.
    plot_sweep_results(root, out)                                                                                                       # Run complete visualization pipeline.
